### PR TITLE
dd demo

### PR DESCRIPTION
**Pull request by win11bot**
Add demo with url https://win11react.github.io/experimental/

### CODE REVIEW

**Comment by andrewstech** [comment]
@blueedgetechno This was generated from #47

**Comment by blueedgetechno** [comment]
Niiice

**Comment by andrewstech** [comment]
> Niiice

Ya still some changes to be made but so far its more helpful then before

**Comment by Lukas-Batema** [comment]
Can it grab an emblem from the shortcut icon meta tag?

**Comment by GitHub-Officials** [comment]
Any Problem Please[[Contact GitHub](https://support.github.com/?tags=dotcom-footer)]

**Comment by blueedgetechno** [comment]
> Any Problem Please[[Contact GitHub](https://support.github.com/?tags=dotcom-footer)]

sus

**Comment by Lukas-Batema** [comment]
dead chat xD

**Pull request closed without merging**
