### PR TITLE
Added Kina OS

### PR DESCRIPTION
**Pull request by Jordtxt**
Name: Kina OS
Type: Game

URL:https://kina-stuff.ha3.repl.co
Icon:   (No ico provided at the time of edit)

### CODE REVIEW

**Comment by notAperson535** [comment]
@Jordtxt sign the cla

**Comment by Lukas-Batema** [comment]
We will not accept this, since we do not know what app it is and we will not go looking for it in the files. Please update your Title and/or description of the PR to include the app name. Thank you!

**Comment by notAperson535** [comment]
@Lukas-Batema the app is Kina OS

**Comment by Lukas-Batema** [comment]
> @Lukas-Batema the app is Kina OS

Never heard of it.

**Comment by notAperson535** [comment]
@Lukas-Batema I was just saying that you could rename the PR to something like "Add Kina OS"

**Comment by Jordtxt** [comment]
Kina OS is like a parody web operating system I made

**Comment by notAperson535** [comment]
> Kina OS is like a parody web operating system I made

@Jordtxt copy this and comment it

I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
