### PR TITLE
Add MK Wiki

### PR DESCRIPTION
**Pull request by RedEdge967**
Added Mortal Kombat Wiki that made by me

### CODE REVIEW

**Comment by MalikIdreesHasanKhan** [comment]
I love how the character descriptions are from wikipedia. Nicely done website

**Comment by RedEdge967** [comment]
> I love how the character descriptions are from wikipedia. Nicely done website

Thank you!

**Comment by Lukas-Batema** [comment]
Why though?

**Comment by andrewstech** [comment]
> Why though?

Why what?

**Pull request merged**
