### PR TITLE
Add Bad Time Simulator

### LINKED ISSUE #162: Bad Time Simulator (tm)
### Name

Bad Time Simulator

### Type

game

### URL

https://jcw87.github.io/c2-sans-fight/

### Icon

_No response_

### Description

Bad Time Simulator is a fangame that recreates Sans' battle from Undertale.

### PR DESCRIPTION
**Pull request by Chameleon-Coder**
This will close #162

### CODE REVIEW

**Comment by Chameleon-Coder** [comment]
**_I have read the CLA document and I hereby sign the CLA_**

**Comment by Chameleon-Coder** [comment]
recheck

**Comment by Chameleon-Coder** [comment]
Can you merge it?

**Review by belubruh123 — APPROVED** [review]
Looks good.

**Pull request closed without merging**
