### PR TITLE
Add BTCLOD

### PR DESCRIPTION
**Pull request by win11bot**
Add BTCLOD with url https://btclod.com/converter-2/. THIS SERVICE IS IN BETA CHANGES MUST BE CHECKED BEFORE MERGING. IMAGES MUST BE MANULLY ADDED.

### CODE REVIEW

**Comment by notAperson535** [comment]
recheck

**Comment by notAperson535** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by notAperson535** [comment]
recheck

**Comment by Posandu** [comment]
https://github.com/win11react/store/issues/76#issuecomment-1052282801

**Pull request closed without merging**
