### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by william33s**
my fav game

### CODE REVIEW

**Comment by RedEdge967** [comment]
@william33s just send a comment telling "I have read the CLA Document and I hereby sign the CLA" and your PR will be accepted if it supports IFrame

**Comment by william33s** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Lukas-Batema** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Lukas-Batema** [comment]
Let's go, I fixed it first try using GitHub's text editor online xD...

**Pull request merged**
