### PR TITLE
Add SocketShot

### PR DESCRIPTION
**Pull request by win11bot**
Add SocketShot with url https://socketshot.io/. THIS SERVICE IS IN BETA CHANGES MUST BE CHECKED BEFORE MERGING. IMAGES MUST BE MANULLY ADDED.

### CODE REVIEW

**Comment by notAperson535** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by notAperson535** [comment]
recheck

**Comment by Young-Fly-Ai** [comment]
recheck

**Comment by notAperson535** [comment]
recheck

**Comment by Lukas-Batema** [comment]
> recheck

Please stop, if you did not commit in this pr, you cannot sign the cla.

**Pull request closed without merging**
