### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by JSMinerOwner**
Can you add my app? Thank you.

### CODE REVIEW

**Comment by JSMinerOwner** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JSMinerOwner** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by JSMinerOwner** [comment]
recheck

**Comment by JSMinerOwner** [comment]
recheck

**Comment by MalikIdreesHasanKhan** [comment]
You dont need to recheck anymore

**Pull request merged**
